AllCops:
  DisabledByDefault: true

Lint/AmbiguousOperator:
  Enabled: false

Metrics/BlockNesting:
  Max: 2

Layout/LineLength:
  AllowURI: true
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 15

# Metrics/ModuleLength:
#   Max: 100

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
